version: 2.1
orbs:
  # orgs contain basc recipes and reproducible actions (install node, aws, etc.)
  node: circleci/node@5.0.2
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.1
  # different jobs are calles later in the workflows sections
jobs:
  build:
    docker:
      # the base image can run most needed actions with orbs
      - image: "cimg/node:16.15"
    steps:
      # install node and checkout code
      - node/install:
          node-version: '16.15'         
      - checkout
      # Use root level package.json to install dependencies in the frontend app
      - run:
          name: Install Front-End Dependencies
          command: |
            cd "Project 4"
            echo "NODE --version" 
            echo $(node --version)
            echo "NPM --version" 
            echo $(npm --version)
            sed -i -e "s/myawsbucket-75139724085/$AWS_BUCKET_NAME/g" ./udagram/udagram-frontend/bin/deploy.sh
            sed -i -e "s/http:\/\/localhost:8080\/api\/v0/http:\/\/udagram-api-dev-dev.us-east-1.elasticbeanstalk.com\/api\/v0/g" ./udagram/udagram-frontend/src/environments/environment.ts
            sed -i -e "s/http:\/\/localhost:8080\/api\/v0/http:\/\/udagram-api-dev-dev.us-east-1.elasticbeanstalk.com\/api\/v0/g" ./udagram/udagram-frontend/src/environments/environment.prod.ts
            npm run frontend:install
      # TODO: Install dependencies in the the backend API          
      - run:
          name: Install API Dependencies
          command: |
           cd "Project 4"
           npm run api:install
      # TODO: Lint the frontend
      - run:
          name: Front-End Lint
          command: |
            cd "Project 4"
            npm run frontend:lint
      # TODO: Build the frontend app
      - run:
          name: Front-End Build
          command: |
            echo "TODO: Build the frontend app"
            cd "Project 4"
            npm run frontend:build
      # TODO: Build the backend API      
      - run:
          name: API Build
          command: |
            echo "TODO: Build the backend API"
            cd "Project 4"
            npm run api:build
  # deploy step will run only after manual approval
  deploy:
    docker:
      - image: "cimg/node:16.15"
      # more setup needed for aws, node, elastic beanstalk
    steps:
      - node/install:
          node-version: '16.15' 
      - eb/setup
      - aws-cli/setup
      - checkout
      - run:
          name: Deploy App
          # TODO: Install, build, deploy in both apps
          command: |
            echo "# TODO: Install, build, deploy in both apps"
            cd "Project 4/udagram/udagram-api/"
            echo $(eb list)
            echo $(aws s3 ls)
            echo "aws s3 cp ./udagram/udagram-frontend/www s3://fullstack-udacity-321723638230/ --recursive"
            
workflows:
  udagram:
    jobs:
      - build
      - hold:
          filters:
            branches:
              only:
                - main
          type: approval
          requires:
            - build
      - deploy:
          context:
            - AWS
          requires:
            - hold
